export const NOTIFICATIONS_QUEUE = Symbol('NOTIFICATIONS_QUEUE');
export const NOTIFICATIONS_DEAD_LETTER_QUEUE = Symbol('NOTIFICATIONS_DEAD_LETTER_QUEUE');
export const INVOICE_REMINDERS_QUEUE = Symbol('INVOICE_REMINDERS_QUEUE');
export const MEDIA_JOBS_QUEUE = Symbol('MEDIA_JOBS_QUEUE');
